version: "3.8"

services:

  web:
    build: ./
    container_name: intunecd
    restart: always
    entrypoint: ./server-entrypoint.sh
    expose:
      - 8080

  redis:
      image: "redis:6.0.5-buster"

  worker:
    build: ./
    entrypoint: celery
    command: -A app.celery worker -l info
    depends_on:
      - "redis"

  beat:
    build: ./
    entrypoint: celery
    command: -A app.celery beat -S sqlalchemy_celery_beat.schedulers:DatabaseScheduler -l info
    depends_on:
      - "redis"
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    command: ["/bin/sh", "-c", "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'"]
    ports:
      - 80:80