version: "3.8"

services:

  web:
    image: ghcr.io/almenscorner/intunecd-monitor:latest
    restart: always
    entrypoint: ./server-entrypoint.sh
    expose:
      - 8080:8080
    volumes:
      - ${WEBAPP_STORAGE_HOME}/db:/intunecd/db
      - ${WEBAPP_STORAGE_HOME}/documentation:/documentation

  redis:
    image: ghcr.io/almenscorner/intunecd-monitor/redis:latest
    restart: always

  worker:
    image: ghcr.io/almenscorner/intunecd-monitor/worker:latest
    restart: always
    entrypoint: celery
    command: -A app.celery worker -l info
    depends_on:
      - "redis"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/db:/intunecd/db
      - ${WEBAPP_STORAGE_HOME}/documentation:/documentation

  beat:
    image: ghcr.io/almenscorner/intunecd-monitor/beat:latest
    restart: always
    entrypoint: celery
    command: -A app.celery beat -S sqlalchemy_celery_beat.schedulers:DatabaseScheduler -l info
    depends_on:
      - "worker"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/db:/intunecd/db
      - ${WEBAPP_STORAGE_HOME}/documentation:/documentation
  
  nginx:
    image: ghcr.io/almenscorner/intunecd-monitor/nginx:latest
    restart: always
    command: ["/bin/sh", "-c", "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'"]
    ports:
      - 80:80