"""initial schema

Revision ID: b5fabaedf83a
Revises: 
Create Date: 2026-03-20 07:04:32.687877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5fabaedf83a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=500), nullable=True),
    sa.Column('key_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('intunecd_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('vault_name', sa.String(), nullable=True),
    sa.Column('update_args', sa.String(), nullable=True),
    sa.Column('backup_args', sa.String(), nullable=True),
    sa.Column('baseline', sa.String(), nullable=True),
    sa.Column('update_feed', sa.String(), nullable=True),
    sa.Column('backup_feed', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('last_update_status', sa.String(), nullable=True),
    sa.Column('last_update_message', sa.String(), nullable=True),
    sa.Column('last_task_id', sa.String(), nullable=True),
    sa.Column('new_branch', sa.String(), nullable=True),
    sa.Column('update_branch', sa.String(), nullable=True),
    sa.Column('create_documentation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('membership_rule', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('tenant', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_average_diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_diffs', sa.Float(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('tenant', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('diffs', sa.String(), nullable=True),
    sa.Column('tenant', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_config_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_count', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('tenant', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_diff_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diff_count', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('tenant', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summary_diff_count')
    op.drop_table('summary_config_count')
    op.drop_table('summary_changes')
    op.drop_table('summary_average_diffs')
    op.drop_table('summary_assignments')
    op.drop_table('intunecd_tenants')
    op.drop_table('api_key')
    # ### end Alembic commands ###
