"""empty message

Revision ID: c0f5d21d08c7
Revises: 
Create Date: 2023-09-28 09:41:02.896763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f5d21d08c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intunecd_tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_documentation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intunecd_tenants', schema=None) as batch_op:
        batch_op.drop_column('create_documentation')

    # ### end Alembic commands ###
