"""empty message

Revision ID: c7c8f17c211a
Revises: c0f5d21d08c7
Create Date: 2023-10-05 10:28:48.974113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c8f17c211a'
down_revision = 'c0f5d21d08c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary_average_diffs', schema=None) as batch_op:
        batch_op.alter_column('average_diffs',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary_average_diffs', schema=None) as batch_op:
        batch_op.alter_column('average_diffs',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
